if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array(
'key' => 'group_5c118c6933c68',
'title' => 'Colors',
'fields' => array(
array(
'key' => 'field_5c118c9aed4c2',
'label' => 'Color',
'name' => 'color',
'type' => 'color_picker',
'instructions' => '',
'required' => 0,
'conditional_logic' => 0,
'wrapper' => array(
'width' => '',
'class' => '',
'id' => '',
),
'default_value' => '',
),
),
'location' => array(
array(
array(
'param' => 'taxonomy',
'operator' => '==',
'value' => 'category',
),
),
),
'menu_order' => 0,
'position' => 'normal',
'style' => 'default',
'label_placement' => 'top',
'instruction_placement' => 'label',
'hide_on_screen' => '',
'active' => 1,
'description' => '',
));

acf_add_local_field_group(array(
'key' => 'group_5c194f87de269',
'title' => 'Partenaires',
'fields' => array(
array(
'key' => 'field_5c195007d4e81',
'label' => 'Identity',
'name' => 'identity',
'type' => 'text',
'instructions' => 'Nom - Prenom',
'required' => 0,
'conditional_logic' => 0,
'wrapper' => array(
'width' => '',
'class' => '',
'id' => '',
),
'default_value' => '',
'placeholder' => '',
'prepend' => '',
'append' => '',
'maxlength' => '',
),
array(
'key' => 'field_5c195034d4e82',
'label' => 'Fonction',
'name' => 'fonction',
'type' => 'text',
'instructions' => 'Fonction dans l\'entreprise',
'required' => 0,
'conditional_logic' => 0,
'wrapper' => array(
'width' => '',
'class' => '',
'id' => '',
),
'default_value' => '',
'placeholder' => '',
'prepend' => '',
'append' => '',
'maxlength' => '',
),
),
'location' => array(
array(
array(
'param' => 'post_type',
'operator' => '==',
'value' => 'partner',
),
),
),
'menu_order' => 0,
'position' => 'normal',
'style' => 'default',
'label_placement' => 'top',
'instruction_placement' => 'label',
'hide_on_screen' => '',
'active' => 1,
'description' => '',
));

acf_add_local_field_group(array(
'key' => 'group_5c1bd484a8751',
'title' => 'Titre assets ( front page )',
'fields' => array(
array(
'key' => 'field_5c1bd490f2ec2',
'label' => 'Titre asset',
'name' => 'titre_asset',
'type' => 'text',
'instructions' => 'Titre box assets',
'required' => 0,
'conditional_logic' => 0,
'wrapper' => array(
'width' => '',
'class' => '',
'id' => '',
),
'default_value' => '',
'placeholder' => '',
'prepend' => '',
'append' => '',
'maxlength' => '',
),
),
'location' => array(
array(
array(
'param' => 'page',
'operator' => '==',
'value' => '6',
),
),
),
'menu_order' => 0,
'position' => 'acf_after_title',
'style' => 'default',
'label_placement' => 'top',
'instruction_placement' => 'label',
'hide_on_screen' => '',
'active' => 1,
'description' => '',
));

acf_add_local_field_group(array(
'key' => 'group_5c18d67f4781e',
'title' => 'Sous titre ( front page )',
'fields' => array(
array(
'key' => 'field_5c18d69267454',
'label' => 'Front sub title',
'name' => 'front_sub_title',
'type' => 'text',
'instructions' => 'Sous titre : page d\'accueil',
'required' => 0,
'conditional_logic' => 0,
'wrapper' => array(
'width' => '',
'class' => '',
'id' => '',
),
'default_value' => '',
'placeholder' => '',
'prepend' => '',
'append' => '',
'maxlength' => '',
),
),
'location' => array(
array(
array(
'param' => 'page_type',
'operator' => '==',
'value' => 'front_page',
),
),
),
'menu_order' => 1,
'position' => 'acf_after_title',
'style' => 'default',
'label_placement' => 'top',
'instruction_placement' => 'label',
'hide_on_screen' => '',
'active' => 1,
'description' => '',
));

acf_add_local_field_group(array(
'key' => 'group_5c19435c78b64',
'title' => 'Titre ( about us )',
'fields' => array(
array(
'key' => 'field_5c1943a8adeef',
'label' => 'About us title',
'name' => 'about_us_title',
'type' => 'text',
'instructions' => '',
'required' => 0,
'conditional_logic' => 0,
'wrapper' => array(
'width' => '',
'class' => '',
'id' => '',
),
'default_value' => '',
'placeholder' => '',
'prepend' => '',
'append' => '',
'maxlength' => '',
),
),
'location' => array(
array(
array(
'param' => 'page',
'operator' => '==',
'value' => '9',
),
),
),
'menu_order' => 1,
'position' => 'acf_after_title',
'style' => 'default',
'label_placement' => 'top',
'instruction_placement' => 'label',
'hide_on_screen' => '',
'active' => 1,
'description' => '',
));

acf_add_local_field_group(array(
'key' => 'group_5c1a97f20175f',
'title' => 'Titre ( contact )',
'fields' => array(
array(
'key' => 'field_5c1a9825ecff8',
'label' => 'Contact title',
'name' => 'contact_title',
'type' => 'text',
'instructions' => '',
'required' => 0,
'conditional_logic' => 0,
'wrapper' => array(
'width' => '',
'class' => '',
'id' => '',
),
'default_value' => '',
'placeholder' => '',
'prepend' => '',
'append' => '',
'maxlength' => '',
),
),
'location' => array(
array(
array(
'param' => 'page',
'operator' => '==',
'value' => '15',
),
),
),
'menu_order' => 1,
'position' => 'acf_after_title',
'style' => 'default',
'label_placement' => 'top',
'instruction_placement' => 'label',
'hide_on_screen' => '',
'active' => 1,
'description' => '',
));

acf_add_local_field_group(array(
'key' => 'group_5c1a9d159addf',
'title' => 'Card list ( contact )',
'fields' => array(
array(
'key' => 'field_5c1a9d4efb26a',
'label' => 'Card_list',
'name' => 'card_list',
'type' => 'repeater',
'instructions' => '',
'required' => 0,
'conditional_logic' => 0,
'wrapper' => array(
'width' => '',
'class' => '',
'id' => '',
),
'collapsed' => '',
'min' => 0,
'max' => 0,
'layout' => 'table',
'button_label' => '',
'sub_fields' => array(
array(
'key' => 'field_5c1a9e1efb26b',
'label' => 'Card list title',
'name' => 'card_list_title',
'type' => 'text',
'instructions' => '',
'required' => 0,
'conditional_logic' => 0,
'wrapper' => array(
'width' => '',
'class' => '',
'id' => '',
),
'default_value' => '',
'placeholder' => '',
'prepend' => '',
'append' => '',
'maxlength' => '',
),
array(
'key' => 'field_5c1a9e3dfb26c',
'label' => 'Card list description',
'name' => 'card_list_description',
'type' => 'text',
'instructions' => '',
'required' => 0,
'conditional_logic' => 0,
'wrapper' => array(
'width' => '',
'class' => '',
'id' => '',
),
'default_value' => '',
'placeholder' => '',
'prepend' => '',
'append' => '',
'maxlength' => '',
),
array(
'key' => 'field_5c1a9e77fb26d',
'label' => 'Card list mail',
'name' => 'card_list_mail',
'type' => 'text',
'instructions' => '',
'required' => 0,
'conditional_logic' => 0,
'wrapper' => array(
'width' => '',
'class' => '',
'id' => '',
),
'default_value' => '',
'placeholder' => '',
'prepend' => '',
'append' => '',
'maxlength' => '',
),
),
),
),
'location' => array(
array(
array(
'param' => 'page',
'operator' => '==',
'value' => '15',
),
),
),
'menu_order' => 2,
'position' => 'normal',
'style' => 'default',
'label_placement' => 'top',
'instruction_placement' => 'label',
'hide_on_screen' => '',
'active' => 1,
'description' => '',
));

acf_add_local_field_group(array(
'key' => 'group_5c1a5edd045f6',
'title' => 'Job box ( about us )',
'fields' => array(
array(
'key' => 'field_5c1a5ff3d1b7d',
'label' => 'Titre job',
'name' => 'titre_job',
'type' => 'text',
'instructions' => 'Titre boite noire',
'required' => 0,
'conditional_logic' => 0,
'wrapper' => array(
'width' => '',
'class' => '',
'id' => '',
),
'default_value' => '',
'placeholder' => '',
'prepend' => '',
'append' => '',
'maxlength' => '',
),
array(
'key' => 'field_5c1a6064d1b7e',
'label' => 'Content job',
'name' => 'content_job',
'type' => 'text',
'instructions' => 'Texte boite noire',
'required' => 0,
'conditional_logic' => 0,
'wrapper' => array(
'width' => '',
'class' => '',
'id' => '',
),
'default_value' => '',
'placeholder' => '',
'prepend' => '',
'append' => '',
'maxlength' => '',
),
array(
'key' => 'field_5c1a60a5d1b80',
'label' => 'Submit job link',
'name' => 'submit_job_link',
'type' => 'link',
'instructions' => 'Url souscription',
'required' => 0,
'conditional_logic' => 0,
'wrapper' => array(
'width' => '',
'class' => '',
'id' => '',
),
'return_format' => 'url',
),
),
'location' => array(
array(
array(
'param' => 'page',
'operator' => '==',
'value' => '9',
),
),
),
'menu_order' => 2,
'position' => 'normal',
'style' => 'default',
'label_placement' => 'top',
'instruction_placement' => 'label',
'hide_on_screen' => '',
'active' => 1,
'description' => '',
));

acf_add_local_field_group(array(
'key' => 'group_5c1a6a18d0523',
'title' => 'Job Inspiration ( about-us )',
'fields' => array(
array(
'key' => 'field_5c1a6a30c3c2a',
'label' => 'Inspiration quote',
'name' => 'inspiration_quote',
'type' => 'text',
'instructions' => 'Phrase motivation',
'required' => 0,
'conditional_logic' => 0,
'wrapper' => array(
'width' => '',
'class' => '',
'id' => '',
),
'default_value' => '',
'placeholder' => '',
'prepend' => '',
'append' => '',
'maxlength' => '',
),
),
'location' => array(
array(
array(
'param' => 'page',
'operator' => '==',
'value' => '9',
),
),
),
'menu_order' => 3,
'position' => 'normal',
'style' => 'default',
'label_placement' => 'top',
'instruction_placement' => 'label',
'hide_on_screen' => '',
'active' => 1,
'description' => '',
));

acf_add_local_field_group(array(
'key' => 'group_5c1a6ca192054',
'title' => 'Check list ( about us )',
'fields' => array(
array(
'key' => 'field_5c1a6cd494190',
'label' => 'Check_list',
'name' => 'check_list',
'type' => 'repeater',
'instructions' => '',
'required' => 0,
'conditional_logic' => 0,
'wrapper' => array(
'width' => '',
'class' => '',
'id' => '',
),
'collapsed' => '',
'min' => 0,
'max' => 0,
'layout' => 'table',
'button_label' => '',
'sub_fields' => array(
array(
'key' => 'field_5c1a6d0994191',
'label' => 'Check list element',
'name' => 'check_list_element',
'type' => 'text',
'instructions' => '',
'required' => 0,
'conditional_logic' => 0,
'wrapper' => array(
'width' => '',
'class' => '',
'id' => '',
),
'default_value' => '',
'placeholder' => '',
'prepend' => '',
'append' => '',
'maxlength' => '',
),
),
),
),
'location' => array(
array(
array(
'param' => 'page',
'operator' => '==',
'value' => '9',
),
),
),
'menu_order' => 4,
'position' => 'normal',
'style' => 'default',
'label_placement' => 'top',
'instruction_placement' => 'label',
'hide_on_screen' => '',
'active' => 1,
'description' => '',
));

endif;